-- @Author : fangcheng
-- @Date   : 2020-03-22 14:25:59
-- @remark : 游戏宏定义

local MACROS = {}

-- 三个平台判断
local TARGET_PALTFORM = cc.Application:getInstance():getTargetPlatform()

MACROS.TARGET_PALTFORM = TARGET_PALTFORM
MACROS.IS_IOS = TARGET_PALTFORM == cc.PLATFORM_OS_IPHONE or TARGET_PALTFORM == cc.PLATFORM_OS_IPAD or TARGET_PALTFORM == cc.PLATFORM_OS_MAC 
MACROS.IS_ANDROID = TARGET_PALTFORM == cc.PLATFORM_OS_ANDROID
MACROS.IS_WINDOWS = TARGET_PALTFORM == cc.PLATFORM_OS_WINDOWS
MACROS.IS_PC = TARGET_PALTFORM == cc.PLATFORM_OS_WINDOWS or TARGET_PALTFORM == cc.PLATFORM_OS_MAC

MACROS.DEBUG = MACROS.IS_PC

return MACROS
