--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create yhmapc10_40
local yhmapc10_40 = cc.Sprite:create("plist/zhuc_ldpi/yhmapc10.png")
yhmapc10_40:setName("yhmapc10_40")
yhmapc10_40:setTag(118)
yhmapc10_40:setCascadeColorEnabled(true)
yhmapc10_40:setCascadeOpacityEnabled(true)
yhmapc10_40:setPosition(-77.5654, 8.5765)
layout = ccui.LayoutComponent:bindLayoutComponent(yhmapc10_40)
layout:setSize({width = 156.0000, height = 229.0000})
layout:setLeftMargin(-155.5654)
layout:setRightMargin(-0.4346)
layout:setTopMargin(-123.0765)
layout:setBottomMargin(-105.9235)
yhmapc10_40:setBlendFunc({src = 1, dst = 771})
Node:addChild(yhmapc10_40)

--Create yhmapc09_39
local yhmapc09_39 = cc.Sprite:create("plist/zhuc_ldpi/yhmapc09.png")
yhmapc09_39:setName("yhmapc09_39")
yhmapc09_39:setTag(119)
yhmapc09_39:setCascadeColorEnabled(true)
yhmapc09_39:setCascadeOpacityEnabled(true)
yhmapc09_39:setPosition(-233.7500, -0.4308)
layout = ccui.LayoutComponent:bindLayoutComponent(yhmapc09_39)
layout:setSize({width = 160.0000, height = 211.0000})
layout:setLeftMargin(-313.7500)
layout:setRightMargin(153.7500)
layout:setTopMargin(-105.0692)
layout:setBottomMargin(-105.9308)
yhmapc09_39:setBlendFunc({src = 1, dst = 771})
Node:addChild(yhmapc09_39)

--Create yhmapc08_38
local yhmapc08_38 = cc.Sprite:create("plist/zhuc_ldpi/yhmapc08.png")
yhmapc08_38:setName("yhmapc08_38")
yhmapc08_38:setTag(120)
yhmapc08_38:setCascadeColorEnabled(true)
yhmapc08_38:setCascadeOpacityEnabled(true)
yhmapc08_38:setPosition(-392.8438, -1.4377)
layout = ccui.LayoutComponent:bindLayoutComponent(yhmapc08_38)
layout:setSize({width = 161.0000, height = 209.0000})
layout:setLeftMargin(-473.3438)
layout:setRightMargin(312.3438)
layout:setTopMargin(-103.0623)
layout:setBottomMargin(-105.9377)
yhmapc08_38:setBlendFunc({src = 1, dst = 771})
Node:addChild(yhmapc08_38)

--Create yhmapc07_37
local yhmapc07_37 = cc.Sprite:create("plist/zhuc_ldpi/yhmapc07.png")
yhmapc07_37:setName("yhmapc07_37")
yhmapc07_37:setTag(121)
yhmapc07_37:setCascadeColorEnabled(true)
yhmapc07_37:setCascadeOpacityEnabled(true)
yhmapc07_37:setPosition(-552.6989, 14.0729)
layout = ccui.LayoutComponent:bindLayoutComponent(yhmapc07_37)
layout:setSize({width = 163.0000, height = 240.0000})
layout:setLeftMargin(-634.1989)
layout:setRightMargin(471.1989)
layout:setTopMargin(-134.0729)
layout:setBottomMargin(-105.9271)
yhmapc07_37:setBlendFunc({src = 1, dst = 771})
Node:addChild(yhmapc07_37)

--Create yhmapc06_36
local yhmapc06_36 = cc.Sprite:create("plist/zhuc_ldpi/yhmapc06.png")
yhmapc06_36:setName("yhmapc06_36")
yhmapc06_36:setTag(122)
yhmapc06_36:setCascadeColorEnabled(true)
yhmapc06_36:setCascadeOpacityEnabled(true)
yhmapc06_36:setPosition(-715.9176, 14.0729)
layout = ccui.LayoutComponent:bindLayoutComponent(yhmapc06_36)
layout:setSize({width = 168.0000, height = 240.0000})
layout:setLeftMargin(-799.9176)
layout:setRightMargin(631.9176)
layout:setTopMargin(-134.0729)
layout:setBottomMargin(-105.9271)
yhmapc06_36:setBlendFunc({src = 1, dst = 771})
Node:addChild(yhmapc06_36)

--Create yhmapc05_35
local yhmapc05_35 = cc.Sprite:create("plist/zhuc_ldpi/yhmapc05.png")
yhmapc05_35:setName("yhmapc05_35")
yhmapc05_35:setTag(123)
yhmapc05_35:setCascadeColorEnabled(true)
yhmapc05_35:setCascadeOpacityEnabled(true)
yhmapc05_35:setPosition(749.3416, -33.9263)
layout = ccui.LayoutComponent:bindLayoutComponent(yhmapc05_35)
layout:setSize({width = 108.0000, height = 144.0000})
layout:setLeftMargin(695.3416)
layout:setRightMargin(-803.3416)
layout:setTopMargin(-38.0737)
layout:setBottomMargin(-105.9263)
yhmapc05_35:setBlendFunc({src = 1, dst = 771})
Node:addChild(yhmapc05_35)

--Create yhmapc04_34
local yhmapc04_34 = cc.Sprite:create("plist/zhuc_ldpi/yhmapc04.png")
yhmapc04_34:setName("yhmapc04_34")
yhmapc04_34:setTag(124)
yhmapc04_34:setCascadeColorEnabled(true)
yhmapc04_34:setCascadeOpacityEnabled(true)
yhmapc04_34:setPosition(619.3506, -25.9240)
layout = ccui.LayoutComponent:bindLayoutComponent(yhmapc04_34)
layout:setSize({width = 155.0000, height = 160.0000})
layout:setLeftMargin(541.8506)
layout:setRightMargin(-696.8506)
layout:setTopMargin(-54.0760)
layout:setBottomMargin(-105.9240)
yhmapc04_34:setBlendFunc({src = 1, dst = 771})
Node:addChild(yhmapc04_34)

--Create yhmapc03_33
local yhmapc03_33 = cc.Sprite:create("plist/zhuc_ldpi/yhmapc03.png")
yhmapc03_33:setName("yhmapc03_33")
yhmapc03_33:setTag(125)
yhmapc03_33:setCascadeColorEnabled(true)
yhmapc03_33:setCascadeOpacityEnabled(true)
yhmapc03_33:setPosition(451.9182, -27.9238)
layout = ccui.LayoutComponent:bindLayoutComponent(yhmapc03_33)
layout:setSize({width = 180.0000, height = 156.0000})
layout:setLeftMargin(361.9182)
layout:setRightMargin(-541.9182)
layout:setTopMargin(-50.0762)
layout:setBottomMargin(-105.9238)
yhmapc03_33:setBlendFunc({src = 1, dst = 771})
Node:addChild(yhmapc03_33)

--Create yhmapc02_32
local yhmapc02_32 = cc.Sprite:create("plist/zhuc_ldpi/yhmapc02.png")
yhmapc02_32:setName("yhmapc02_32")
yhmapc02_32:setTag(126)
yhmapc02_32:setCascadeColorEnabled(true)
yhmapc02_32:setCascadeOpacityEnabled(true)
yhmapc02_32:setPosition(272.8679, -6.4319)
layout = ccui.LayoutComponent:bindLayoutComponent(yhmapc02_32)
layout:setSize({width = 181.0000, height = 199.0000})
layout:setLeftMargin(182.3679)
layout:setRightMargin(-363.3679)
layout:setTopMargin(-93.0681)
layout:setBottomMargin(-105.9319)
yhmapc02_32:setBlendFunc({src = 1, dst = 771})
Node:addChild(yhmapc02_32)

--Create yhmapc01_31
local yhmapc01_31 = cc.Sprite:create("plist/zhuc_ldpi/yhmapc01.png")
yhmapc01_31:setName("yhmapc01_31")
yhmapc01_31:setTag(127)
yhmapc01_31:setCascadeColorEnabled(true)
yhmapc01_31:setCascadeOpacityEnabled(true)
yhmapc01_31:setPosition(90.9312, 14.0729)
layout = ccui.LayoutComponent:bindLayoutComponent(yhmapc01_31)
layout:setSize({width = 186.0000, height = 240.0000})
layout:setLeftMargin(-2.0688)
layout:setRightMargin(-183.9312)
layout:setTopMargin(-134.0729)
layout:setBottomMargin(-105.9271)
yhmapc01_31:setBlendFunc({src = 1, dst = 771})
Node:addChild(yhmapc01_31)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

