--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create sprite_BG
local sprite_BG = cc.Sprite:create("cont/adui10.png")
sprite_BG:setName("sprite_BG")
sprite_BG:setTag(234)
sprite_BG:setCascadeColorEnabled(true)
sprite_BG:setCascadeOpacityEnabled(true)
sprite_BG:setPosition(182.1176, 161.8839)
layout = ccui.LayoutComponent:bindLayoutComponent(sprite_BG)
layout:setPositionPercentX(0.1603)
layout:setPositionPercentY(0.2529)
layout:setPercentWidth(0.4930)
layout:setPercentHeight(0.8750)
layout:setSize({width = 560.0000, height = 560.0000})
layout:setLeftMargin(-97.8824)
layout:setRightMargin(673.8824)
layout:setTopMargin(198.1161)
layout:setBottomMargin(-118.1161)
sprite_BG:setBlendFunc({src = 1, dst = 771})
Scene:addChild(sprite_BG)

--Create sprite_Ori
local sprite_Ori = cc.Sprite:create("cont/adui10_2.png")
sprite_Ori:setName("sprite_Ori")
sprite_Ori:setTag(235)
sprite_Ori:setCascadeColorEnabled(true)
sprite_Ori:setCascadeOpacityEnabled(true)
sprite_Ori:setPosition(280.0000, 280.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sprite_Ori)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3946)
layout:setPercentHeight(0.3946)
layout:setSize({width = 221.0000, height = 221.0000})
layout:setLeftMargin(169.5000)
layout:setRightMargin(169.5000)
layout:setTopMargin(169.5000)
layout:setBottomMargin(169.5000)
sprite_Ori:setBlendFunc({src = 1, dst = 771})
sprite_BG:addChild(sprite_Ori)

--Create sprite_Red
local sprite_Red = cc.Sprite:create("cont/adui35.png")
sprite_Red:setName("sprite_Red")
sprite_Red:setTag(236)
sprite_Red:setCascadeColorEnabled(true)
sprite_Red:setCascadeOpacityEnabled(true)
sprite_Red:setPosition(280.0000, 280.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sprite_Red)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3946)
layout:setPercentHeight(0.3946)
layout:setSize({width = 221.0000, height = 221.0000})
layout:setLeftMargin(169.5000)
layout:setRightMargin(169.5000)
layout:setTopMargin(169.5000)
layout:setBottomMargin(169.5000)
sprite_Red:setBlendFunc({src = 1, dst = 771})
sprite_BG:addChild(sprite_Red)

--Create sprite_Move
local sprite_Move = cc.Sprite:create("cont/joyk2.png")
sprite_Move:setName("sprite_Move")
sprite_Move:setTag(233)
sprite_Move:setCascadeColorEnabled(true)
sprite_Move:setCascadeOpacityEnabled(true)
sprite_Move:setPosition(182.1193, 161.8858)
layout = ccui.LayoutComponent:bindLayoutComponent(sprite_Move)
layout:setPositionPercentX(0.1603)
layout:setPositionPercentY(0.2529)
layout:setPercentWidth(0.5282)
layout:setPercentHeight(0.9375)
layout:setSize({width = 600.0000, height = 600.0000})
layout:setLeftMargin(-117.8807)
layout:setRightMargin(653.8807)
layout:setTopMargin(178.1142)
layout:setBottomMargin(-138.1142)
sprite_Move:setBlendFunc({src = 1, dst = 771})
Scene:addChild(sprite_Move)

--Create Button_ChangeWeapon
local Button_ChangeWeapon = ccui.Button:create()
Button_ChangeWeapon:ignoreContentAdaptWithSize(false)
Button_ChangeWeapon:loadTextureNormal("cont/icon2_2.png",0)
Button_ChangeWeapon:loadTexturePressed("cont/icon2_1.png",0)
Button_ChangeWeapon:setTitleFontSize(14)
Button_ChangeWeapon:setTitleText("Button")
Button_ChangeWeapon:setTitleColor({r = 65, g = 65, b = 70})
Button_ChangeWeapon:setScale9Enabled(true)
Button_ChangeWeapon:setCapInsets({x = 15, y = 11, width = 80, height = 88})
Button_ChangeWeapon:setBright(false)
Button_ChangeWeapon:setTouchEnabled(false);
Button_ChangeWeapon:setLayoutComponentEnabled(true)
Button_ChangeWeapon:setName("Button_ChangeWeapon")
Button_ChangeWeapon:setTag(249)
Button_ChangeWeapon:setCascadeColorEnabled(true)
Button_ChangeWeapon:setCascadeOpacityEnabled(true)
Button_ChangeWeapon:setVisible(false)
Button_ChangeWeapon:setPosition(695.8053, 88.5668)
if callBackProvider~=nil then
      Button_ChangeWeapon:addClickEventListener(callBackProvider("playerControlUI.lua", Button_ChangeWeapon, "onClickChangeWeapon"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_ChangeWeapon)
layout:setPositionPercentX(0.6125)
layout:setPositionPercentY(0.1384)
layout:setPercentWidth(0.0968)
layout:setPercentHeight(0.1719)
layout:setSize({width = 110.0000, height = 110.0000})
layout:setLeftMargin(640.8053)
layout:setRightMargin(385.1947)
layout:setTopMargin(496.4332)
layout:setBottomMargin(33.5668)
Scene:addChild(Button_ChangeWeapon)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("cont/atk_but.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 100, height = 108})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(19)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(1013.3350, 105.6456)
if callBackProvider~=nil then
      Button_1:addClickEventListener(callBackProvider("playerControlUI.lua", Button_1, "onClickAttack"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.8920)
layout:setPositionPercentY(0.1651)
layout:setPercentWidth(0.1144)
layout:setPercentHeight(0.2031)
layout:setSize({width = 130.0000, height = 130.0000})
layout:setLeftMargin(948.3350)
layout:setRightMargin(57.6650)
layout:setTopMargin(469.3544)
layout:setBottomMargin(40.6456)
Scene:addChild(Button_1)

--Create Button_2
local Button_2 = ccui.Button:create()
Button_2:ignoreContentAdaptWithSize(false)
Button_2:loadTextureNormal("Default/Button_Normal.png",0)
Button_2:loadTexturePressed("Default/Button_Press.png",0)
Button_2:loadTextureDisabled("Default/Button_Disable.png",0)
Button_2:setTitleFontSize(14)
Button_2:setTitleText("Button")
Button_2:setTitleColor({r = 65, g = 65, b = 70})
Button_2:setScale9Enabled(true)
Button_2:setCapInsets({x = 15, y = 11, width = 16, height = 14})
Button_2:setLayoutComponentEnabled(true)
Button_2:setName("Button_2")
Button_2:setTag(68)
Button_2:setCascadeColorEnabled(true)
Button_2:setCascadeOpacityEnabled(true)
Button_2:setPosition(84.3111, 583.7205)
if callBackProvider~=nil then
      Button_2:addClickEventListener(callBackProvider("playerControlUI.lua", Button_2, "onClickOpenDebug"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_2)
layout:setPositionPercentX(0.0742)
layout:setPositionPercentY(0.9121)
layout:setPercentWidth(0.0630)
layout:setPercentHeight(0.0642)
layout:setSize({width = 71.5457, height = 41.1091})
layout:setLeftMargin(48.5383)
layout:setRightMargin(1015.9160)
layout:setTopMargin(35.7249)
layout:setBottomMargin(563.1660)
Scene:addChild(Button_2)

--Create Button_Skill1
local Button_Skill1 = ccui.Button:create()
Button_Skill1:ignoreContentAdaptWithSize(false)
Button_Skill1:loadTextureNormal("cont/taidaoay01.png",0)
Button_Skill1:setTitleFontSize(14)
Button_Skill1:setTitleText("Button")
Button_Skill1:setTitleColor({r = 65, g = 65, b = 70})
Button_Skill1:setScale9Enabled(true)
Button_Skill1:setCapInsets({x = 15, y = 11, width = 40, height = 48})
Button_Skill1:setLayoutComponentEnabled(true)
Button_Skill1:setName("Button_Skill1")
Button_Skill1:setTag(41)
Button_Skill1:setCascadeColorEnabled(true)
Button_Skill1:setCascadeOpacityEnabled(true)
Button_Skill1:setPosition(847.5917, 83.9316)
Button_Skill1.UserData = {}
Button_Skill1.UserData[1] = [==========[1]==========]
if callBackProvider~=nil then
      Button_Skill1:addClickEventListener(callBackProvider("playerControlUI.lua", Button_Skill1, "onClickSkill"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_Skill1)
layout:setPositionPercentX(0.7461)
layout:setPositionPercentY(0.1311)
layout:setPercentWidth(0.0616)
layout:setPercentHeight(0.1094)
layout:setSize({width = 70.0000, height = 70.0000})
layout:setLeftMargin(812.5917)
layout:setRightMargin(253.4083)
layout:setTopMargin(521.0684)
layout:setBottomMargin(48.9316)
Scene:addChild(Button_Skill1)

--Create Button_Skill2
local Button_Skill2 = ccui.Button:create()
Button_Skill2:ignoreContentAdaptWithSize(false)
Button_Skill2:loadTextureNormal("cont/taidaoay01.png",0)
Button_Skill2:setTitleFontSize(14)
Button_Skill2:setTitleText("Button")
Button_Skill2:setTitleColor({r = 65, g = 65, b = 70})
Button_Skill2:setScale9Enabled(true)
Button_Skill2:setCapInsets({x = 15, y = 11, width = 40, height = 48})
Button_Skill2:setLayoutComponentEnabled(true)
Button_Skill2:setName("Button_Skill2")
Button_Skill2:setTag(42)
Button_Skill2:setCascadeColorEnabled(true)
Button_Skill2:setCascadeOpacityEnabled(true)
Button_Skill2:setPosition(880.0519, 200.4197)
Button_Skill2.UserData = {}
Button_Skill2.UserData[1] = [==========[2]==========]
if callBackProvider~=nil then
      Button_Skill2:addClickEventListener(callBackProvider("playerControlUI.lua", Button_Skill2, "onClickSkill"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_Skill2)
layout:setPositionPercentX(0.7747)
layout:setPositionPercentY(0.3132)
layout:setPercentWidth(0.0616)
layout:setPercentHeight(0.1094)
layout:setSize({width = 70.0000, height = 70.0000})
layout:setLeftMargin(845.0519)
layout:setRightMargin(220.9481)
layout:setTopMargin(404.5803)
layout:setBottomMargin(165.4197)
Scene:addChild(Button_Skill2)

--Create Button_Skill3
local Button_Skill3 = ccui.Button:create()
Button_Skill3:ignoreContentAdaptWithSize(false)
Button_Skill3:loadTextureNormal("cont/taidaoay01.png",0)
Button_Skill3:setTitleFontSize(14)
Button_Skill3:setTitleText("Button")
Button_Skill3:setTitleColor({r = 65, g = 65, b = 70})
Button_Skill3:setScale9Enabled(true)
Button_Skill3:setCapInsets({x = 15, y = 11, width = 40, height = 48})
Button_Skill3:setLayoutComponentEnabled(true)
Button_Skill3:setName("Button_Skill3")
Button_Skill3:setTag(43)
Button_Skill3:setCascadeColorEnabled(true)
Button_Skill3:setCascadeOpacityEnabled(true)
Button_Skill3:setPosition(969.2545, 261.3481)
Button_Skill3.UserData = {}
Button_Skill3.UserData[1] = [==========[3]==========]
if callBackProvider~=nil then
      Button_Skill3:addClickEventListener(callBackProvider("playerControlUI.lua", Button_Skill3, "onClickSkill"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_Skill3)
layout:setPositionPercentX(0.8532)
layout:setPositionPercentY(0.4084)
layout:setPercentWidth(0.0616)
layout:setPercentHeight(0.1094)
layout:setSize({width = 70.0000, height = 70.0000})
layout:setLeftMargin(934.2545)
layout:setRightMargin(131.7455)
layout:setTopMargin(343.6519)
layout:setBottomMargin(226.3481)
Scene:addChild(Button_Skill3)

--Create Button_Skill4
local Button_Skill4 = ccui.Button:create()
Button_Skill4:ignoreContentAdaptWithSize(false)
Button_Skill4:loadTextureNormal("cont/taidaoay01.png",0)
Button_Skill4:setTitleFontSize(14)
Button_Skill4:setTitleText("Button")
Button_Skill4:setTitleColor({r = 65, g = 65, b = 70})
Button_Skill4:setScale9Enabled(true)
Button_Skill4:setCapInsets({x = 15, y = 11, width = 40, height = 48})
Button_Skill4:setLayoutComponentEnabled(true)
Button_Skill4:setName("Button_Skill4")
Button_Skill4:setTag(44)
Button_Skill4:setCascadeColorEnabled(true)
Button_Skill4:setCascadeOpacityEnabled(true)
Button_Skill4:setPosition(1078.5530, 265.5331)
Button_Skill4.UserData = {}
Button_Skill4.UserData[1] = [==========[4]==========]
if callBackProvider~=nil then
      Button_Skill4:addClickEventListener(callBackProvider("playerControlUI.lua", Button_Skill4, "onClickSkill"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_Skill4)
layout:setPositionPercentX(0.9494)
layout:setPositionPercentY(0.4149)
layout:setPercentWidth(0.0616)
layout:setPercentHeight(0.1094)
layout:setSize({width = 70.0000, height = 70.0000})
layout:setLeftMargin(1043.5530)
layout:setRightMargin(22.4473)
layout:setTopMargin(339.4669)
layout:setBottomMargin(230.5331)
Scene:addChild(Button_Skill4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

