--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create btn_left
local btn_left = ccui.Button:create()
btn_left:ignoreContentAdaptWithSize(false)
btn_left:loadTextureNormal("Default/Button_Normal.png",0)
btn_left:loadTexturePressed("Default/Button_Press.png",0)
btn_left:loadTextureDisabled("Default/Button_Disable.png",0)
btn_left:setTitleFontSize(14)
btn_left:setTitleText("Button")
btn_left:setTitleColor({r = 65, g = 65, b = 70})
btn_left:setScale9Enabled(true)
btn_left:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btn_left:setLayoutComponentEnabled(true)
btn_left:setName("btn_left")
btn_left:setTag(2)
btn_left:setCascadeColorEnabled(true)
btn_left:setCascadeOpacityEnabled(true)
btn_left:setPosition(227.2000, 190.0147)
if callBackProvider~=nil then
      btn_left:addTouchEventListener(callBackProvider("UI_TestScene.lua", btn_left, "onTouchLeft"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_left)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.2000)
layout:setPositionPercentY(0.2969)
layout:setPercentWidth(0.1499)
layout:setPercentHeight(0.1887)
layout:setSize({width = 170.3133, height = 120.7590})
layout:setLeftMargin(142.0434)
layout:setRightMargin(823.6434)
layout:setTopMargin(389.6058)
layout:setBottomMargin(129.6352)
Scene:addChild(btn_left)

--Create btn_right
local btn_right = ccui.Button:create()
btn_right:ignoreContentAdaptWithSize(false)
btn_right:loadTextureNormal("Default/Button_Normal.png",0)
btn_right:loadTexturePressed("Default/Button_Press.png",0)
btn_right:loadTextureDisabled("Default/Button_Disable.png",0)
btn_right:setTitleFontSize(14)
btn_right:setTitleText("Button")
btn_right:setTitleColor({r = 65, g = 65, b = 70})
btn_right:setScale9Enabled(true)
btn_right:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btn_right:setLayoutComponentEnabled(true)
btn_right:setName("btn_right")
btn_right:setTag(3)
btn_right:setCascadeColorEnabled(true)
btn_right:setCascadeOpacityEnabled(true)
btn_right:setPosition(908.8000, 190.0147)
if callBackProvider~=nil then
      btn_right:addTouchEventListener(callBackProvider("UI_TestScene.lua", btn_right, "onTouchRight"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_right)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.8000)
layout:setPositionPercentY(0.2969)
layout:setPercentWidth(0.1499)
layout:setPercentHeight(0.1887)
layout:setSize({width = 170.3133, height = 120.7590})
layout:setLeftMargin(823.6433)
layout:setRightMargin(142.0433)
layout:setTopMargin(389.6058)
layout:setBottomMargin(129.6352)
Scene:addChild(btn_right)

--Create text_left
local text_left = ccui.Text:create()
text_left:ignoreContentAdaptWithSize(true)
text_left:setTextAreaSize({width = 0, height = 0})
text_left:setFontName("fonts/huakang.ttf")
text_left:setFontSize(35)
text_left:setString([[<<点击左侧按钮<<]])
text_left:setLayoutComponentEnabled(true)
text_left:setName("text_left")
text_left:setTag(4)
text_left:setCascadeColorEnabled(true)
text_left:setCascadeOpacityEnabled(true)
text_left:setPosition(227.2000, 551.6519)
text_left:setTextColor({r = 255, g = 192, b = 203})
layout = ccui.LayoutComponent:bindLayoutComponent(text_left)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.2000)
layout:setPositionPercentY(0.8620)
layout:setPercentWidth(0.2562)
layout:setPercentHeight(0.0547)
layout:setSize({width = 291.0000, height = 35.0000})
layout:setLeftMargin(81.7000)
layout:setRightMargin(763.3000)
layout:setTopMargin(70.8481)
layout:setBottomMargin(534.1519)
Scene:addChild(text_left)

--Create text_right
local text_right = ccui.Text:create()
text_right:ignoreContentAdaptWithSize(true)
text_right:setTextAreaSize({width = 0, height = 0})
text_right:setFontName("fonts/huakang.ttf")
text_right:setFontSize(35)
text_right:setString([[<<点击右侧按钮>>]])
text_right:setLayoutComponentEnabled(true)
text_right:setName("text_right")
text_right:setTag(5)
text_right:setCascadeColorEnabled(true)
text_right:setCascadeOpacityEnabled(true)
text_right:setPosition(908.8000, 551.6519)
text_right:setTextColor({r = 173, g = 216, b = 230})
layout = ccui.LayoutComponent:bindLayoutComponent(text_right)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.8000)
layout:setPositionPercentY(0.8620)
layout:setPercentWidth(0.2562)
layout:setPercentHeight(0.0547)
layout:setSize({width = 291.0000, height = 35.0000})
layout:setLeftMargin(763.3000)
layout:setRightMargin(81.7000)
layout:setTopMargin(70.8481)
layout:setBottomMargin(534.1519)
Scene:addChild(text_right)

--Create btn_global
local btn_global = ccui.Button:create()
btn_global:ignoreContentAdaptWithSize(false)
btn_global:loadTextureNormal("Default/Button_Normal.png",0)
btn_global:loadTexturePressed("Default/Button_Press.png",0)
btn_global:loadTextureDisabled("Default/Button_Disable.png",0)
btn_global:setTitleFontSize(14)
btn_global:setTitleText("Button")
btn_global:setTitleColor({r = 65, g = 65, b = 70})
btn_global:setScale9Enabled(true)
btn_global:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btn_global:setLayoutComponentEnabled(true)
btn_global:setName("btn_global")
btn_global:setTag(6)
btn_global:setCascadeColorEnabled(true)
btn_global:setCascadeOpacityEnabled(true)
btn_global:setPosition(567.9998, 118.9464)
if callBackProvider~=nil then
      btn_global:addClickEventListener(callBackProvider("UI_TestScene.lua", btn_global, "onClickBtnGlobal"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_global)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1859)
layout:setPercentWidth(0.1078)
layout:setPercentHeight(0.0912)
layout:setSize({width = 122.4191, height = 58.3667})
layout:setLeftMargin(506.7902)
layout:setRightMargin(506.7906)
layout:setTopMargin(491.8703)
layout:setBottomMargin(89.7630)
Scene:addChild(btn_global)

--Create text_global
local text_global = ccui.Text:create()
text_global:ignoreContentAdaptWithSize(true)
text_global:setTextAreaSize({width = 0, height = 0})
text_global:setFontName("fonts/huakang.ttf")
text_global:setFontSize(35)
text_global:setString([[<<点击左侧按钮<<]])
text_global:setLayoutComponentEnabled(true)
text_global:setName("text_global")
text_global:setTag(7)
text_global:setCascadeColorEnabled(true)
text_global:setCascadeOpacityEnabled(true)
text_global:setPosition(568.0000, 189.9692)
text_global:setTextColor({r = 30, g = 144, b = 255})
layout = ccui.LayoutComponent:bindLayoutComponent(text_global)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2968)
layout:setPercentWidth(0.2562)
layout:setPercentHeight(0.0547)
layout:setSize({width = 291.0000, height = 35.0000})
layout:setLeftMargin(422.5000)
layout:setRightMargin(422.5000)
layout:setTopMargin(432.5308)
layout:setBottomMargin(172.4692)
Scene:addChild(text_global)

--Create btn_nomal
local btn_nomal = ccui.Button:create()
btn_nomal:ignoreContentAdaptWithSize(false)
btn_nomal:loadTextureNormal("Default/Button_Normal.png",0)
btn_nomal:loadTexturePressed("Default/Button_Press.png",0)
btn_nomal:loadTextureDisabled("Default/Button_Disable.png",0)
btn_nomal:setTitleFontSize(14)
btn_nomal:setTitleText("Button")
btn_nomal:setTitleColor({r = 65, g = 65, b = 70})
btn_nomal:setScale9Enabled(true)
btn_nomal:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btn_nomal:setLayoutComponentEnabled(true)
btn_nomal:setName("btn_nomal")
btn_nomal:setTag(8)
btn_nomal:setCascadeColorEnabled(true)
btn_nomal:setCascadeOpacityEnabled(true)
btn_nomal:setPosition(573.3185, 380.6292)
if callBackProvider~=nil then
      btn_nomal:addTouchEventListener(callBackProvider("UI_TestScene.lua", btn_nomal, "onTouchBtnNormal"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_nomal)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5047)
layout:setPositionPercentY(0.5947)
layout:setPercentWidth(0.1078)
layout:setPercentHeight(0.0912)
layout:setSize({width = 122.4191, height = 58.3667})
layout:setLeftMargin(512.1090)
layout:setRightMargin(501.4719)
layout:setTopMargin(230.1875)
layout:setBottomMargin(351.4458)
Scene:addChild(btn_nomal)

--Create text_normal
local text_normal = ccui.Text:create()
text_normal:ignoreContentAdaptWithSize(true)
text_normal:setTextAreaSize({width = 0, height = 0})
text_normal:setFontName("fonts/huakang.ttf")
text_normal:setFontSize(35)
text_normal:setString([[<<点击普通按钮<<]])
text_normal:setLayoutComponentEnabled(true)
text_normal:setName("text_normal")
text_normal:setTag(9)
text_normal:setCascadeColorEnabled(true)
text_normal:setCascadeOpacityEnabled(true)
text_normal:setPosition(573.3196, 451.6513)
text_normal:setTextColor({r = 0, g = 128, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(text_normal)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5047)
layout:setPositionPercentY(0.7057)
layout:setPercentWidth(0.2562)
layout:setPercentHeight(0.0547)
layout:setSize({width = 291.0000, height = 35.0000})
layout:setLeftMargin(427.8196)
layout:setRightMargin(417.1804)
layout:setTopMargin(170.8487)
layout:setBottomMargin(434.1513)
Scene:addChild(text_normal)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

