--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create tianyq4_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("map1/map1qjc20.plist")
local tianyq4_1 = cc.Sprite:createWithSpriteFrameName("tianyq4.png")
tianyq4_1:setName("tianyq4_1")
tianyq4_1:setTag(89)
tianyq4_1:setCascadeColorEnabled(true)
tianyq4_1:setCascadeOpacityEnabled(true)
tianyq4_1:setPosition(104.0152, 36.8383)
layout = ccui.LayoutComponent:bindLayoutComponent(tianyq4_1)
layout:setSize({width = 214.0000, height = 71.0000})
layout:setLeftMargin(-2.9848)
layout:setRightMargin(-211.0152)
layout:setTopMargin(-72.3383)
layout:setBottomMargin(1.3383)
tianyq4_1:setBlendFunc({src = 1, dst = 771})
Node:addChild(tianyq4_1)

--Create tianyq3_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("map1/map1qjc20.plist")
local tianyq3_2 = cc.Sprite:createWithSpriteFrameName("tianyq3.png")
tianyq3_2:setName("tianyq3_2")
tianyq3_2:setTag(90)
tianyq3_2:setCascadeColorEnabled(true)
tianyq3_2:setCascadeOpacityEnabled(true)
tianyq3_2:setPosition(293.9604, 22.3384)
layout = ccui.LayoutComponent:bindLayoutComponent(tianyq3_2)
layout:setSize({width = 175.0000, height = 42.0000})
layout:setLeftMargin(206.4604)
layout:setRightMargin(-381.4604)
layout:setTopMargin(-43.3384)
layout:setBottomMargin(1.3384)
tianyq3_2:setBlendFunc({src = 1, dst = 771})
Node:addChild(tianyq3_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

