--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 700.0000, height = 100.0000})

--Create FileNode_1
innerCSD = require("windows.home.Node")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1 = innerProject.root
FileNode_1.animation = innerProject.animation
FileNode_1:setName("FileNode_1")
FileNode_1:setTag(78)
FileNode_1:setCascadeColorEnabled(true)
FileNode_1:setCascadeOpacityEnabled(true)
FileNode_1:setPosition(55.0825, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0787)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(55.0825)
layout:setRightMargin(644.9175)
layout:setTopMargin(50.0000)
layout:setBottomMargin(50.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1:runAction(innerProject.animation)
Layer:addChild(FileNode_1)

--Create FileNode_1_0
innerCSD = require("windows.home.Node")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1_0 = innerProject.root
FileNode_1_0.animation = innerProject.animation
FileNode_1_0:setName("FileNode_1_0")
FileNode_1_0:setTag(90)
FileNode_1_0:setCascadeColorEnabled(true)
FileNode_1_0:setCascadeOpacityEnabled(true)
FileNode_1_0:setPosition(173.4875, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1_0)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2478)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(173.4875)
layout:setRightMargin(526.5125)
layout:setTopMargin(50.0000)
layout:setBottomMargin(50.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1_0:runAction(innerProject.animation)
Layer:addChild(FileNode_1_0)

--Create FileNode_1_1
innerCSD = require("windows.home.Node")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1_1 = innerProject.root
FileNode_1_1.animation = innerProject.animation
FileNode_1_1:setName("FileNode_1_1")
FileNode_1_1:setTag(102)
FileNode_1_1:setCascadeColorEnabled(true)
FileNode_1_1:setCascadeOpacityEnabled(true)
FileNode_1_1:setPosition(291.8925, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1_1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.4170)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(291.8925)
layout:setRightMargin(408.1075)
layout:setTopMargin(50.0000)
layout:setBottomMargin(50.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1_1:runAction(innerProject.animation)
Layer:addChild(FileNode_1_1)

--Create FileNode_1_2
innerCSD = require("windows.home.Node")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1_2 = innerProject.root
FileNode_1_2.animation = innerProject.animation
FileNode_1_2:setName("FileNode_1_2")
FileNode_1_2:setTag(114)
FileNode_1_2:setCascadeColorEnabled(true)
FileNode_1_2:setCascadeOpacityEnabled(true)
FileNode_1_2:setPosition(410.2976, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1_2)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5861)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(410.2976)
layout:setRightMargin(289.7024)
layout:setTopMargin(50.0000)
layout:setBottomMargin(50.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1_2:runAction(innerProject.animation)
Layer:addChild(FileNode_1_2)

--Create FileNode_1_3
innerCSD = require("windows.home.Node")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1_3 = innerProject.root
FileNode_1_3.animation = innerProject.animation
FileNode_1_3:setName("FileNode_1_3")
FileNode_1_3:setTag(126)
FileNode_1_3:setCascadeColorEnabled(true)
FileNode_1_3:setCascadeOpacityEnabled(true)
FileNode_1_3:setPosition(528.7025, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1_3)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.7553)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(528.7025)
layout:setRightMargin(171.2975)
layout:setTopMargin(50.0000)
layout:setBottomMargin(50.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1_3:runAction(innerProject.animation)
Layer:addChild(FileNode_1_3)

--Create FileNode_1_4
innerCSD = require("windows.home.Node")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1_4 = innerProject.root
FileNode_1_4.animation = innerProject.animation
FileNode_1_4:setName("FileNode_1_4")
FileNode_1_4:setTag(138)
FileNode_1_4:setCascadeColorEnabled(true)
FileNode_1_4:setCascadeOpacityEnabled(true)
FileNode_1_4:setPosition(647.1075, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1_4)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.9244)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(647.1075)
layout:setRightMargin(52.8925)
layout:setTopMargin(50.0000)
layout:setBottomMargin(50.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1_4:runAction(innerProject.animation)
Layer:addChild(FileNode_1_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

